### ISSUE TITLE
new logo proposal

### ISSUE THREAD

**Issue by mansya** [andriannus/sehatyuk-spa#1]
Good day Sir I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before i begin my design. Hoping for your positive feedback. Thanks

**Comment by andriannus** [comment]
Hi, sorry for a long time in replying to your message.
This project only learns for me. Not for publication. Thank you for your help. It seems like I don't need it for this project.
